package me.penguinx13.wapi;

import org.bukkit.entity.EntityType;
import org.bukkit.event.Listener;

public class EntityName implements Listener {
    public static EntityType getType(String entityName){
        return switch (entityName) {
            case "Падающий предмет" -> EntityType.DROPPED_ITEM;
            case "Опыт" -> EntityType.EXPERIENCE_ORB;
            case "Облачность эффекта" -> EntityType.AREA_EFFECT_CLOUD;
            case "Древний страж" -> EntityType.ELDER_GUARDIAN;
            case "Визер скелет" -> EntityType.WITHER_SKELETON;
            case "Зимогор" -> EntityType.STRAY;
            case "Яйцо" -> EntityType.EGG;
            case "Пводок" -> EntityType.LEASH_HITCH;
            case "Картина" -> EntityType.PAINTING;
            case "Стрела" -> EntityType.ARROW;
            case "Снежок" -> EntityType.SNOWBALL;
            case "Огненный шар" -> EntityType.FIREBALL;
            case "Маленький огненный шар" -> EntityType.SMALL_FIREBALL;
            case "Жемчуг Края" -> EntityType.ENDER_PEARL;
            case "Сигнал Края" -> EntityType.ENDER_SIGNAL;
            case "Бутылка с зельем" -> EntityType.SPLASH_POTION;
            case "Бутылка с опытом" -> EntityType.THROWN_EXP_BOTTLE;
            case "Рамка" -> EntityType.ITEM_FRAME;
            case "Череп визера" -> EntityType.WITHER_SKULL;
            case "Горящий динамит" -> EntityType.PRIMED_TNT;
            case "Падающий блок" -> EntityType.FALLING_BLOCK;
            case "Фейерверк" -> EntityType.FIREWORK;
            case "Спектральная стрела" -> EntityType.SPECTRAL_ARROW;
            case "Снаряд шалкера" -> EntityType.SHULKER_BULLET;
            case "Огненный шар дракона" -> EntityType.DRAGON_FIREBALL;
            case "Зомби житель" -> EntityType.ZOMBIE_VILLAGER;
            case "Скелет конь" -> EntityType.SKELETON_HORSE;
            case "Зомби конь" -> EntityType.ZOMBIE_HORSE;
            case "Стойка для брони" -> EntityType.ARMOR_STAND;
            case "Осел" -> EntityType.DONKEY;
            case "Мул" -> EntityType.MULE;
            case "Клыки призывателя" -> EntityType.EVOKER_FANGS;
            case "Призыватель" -> EntityType.EVOKER;
            case "Досаждатель" -> EntityType.VEX;
            case "Разбойник" -> EntityType.VINDICATOR;
            case "Иллюзионист" -> EntityType.ILLUSIONER;
            case "Вагонетка с комендным блоком" -> EntityType.MINECART_COMMAND;
            case "Лодка" -> EntityType.BOAT;
            case "Вагонетка" -> EntityType.MINECART;
            case "Вагонетка с сундуком" -> EntityType.MINECART_CHEST;
            case "Вагонетка с печкой" -> EntityType.MINECART_FURNACE;
            case "Вагонетка с ТНТ" -> EntityType.MINECART_TNT;
            case "Вагонетка с воронкой" -> EntityType.MINECART_HOPPER;
            case "Вагонетка с спавнером" -> EntityType.MINECART_MOB_SPAWNER;
            case "Крипер" -> EntityType.CREEPER;
            case "Скелет" -> EntityType.SKELETON;
            case "Паук" -> EntityType.SPIDER;
            case "Зомби гигант" -> EntityType.GIANT;
            case "Зомби" -> EntityType.ZOMBIE;
            case "Слизь" -> EntityType.SLIME;
            case "Гаст" -> EntityType.GHAST;
            case "Свинозомби" -> EntityType.ZOGLIN;
            case "Эндермен" -> EntityType.ENDERMAN;
            case "Пещерный паук" -> EntityType.CAVE_SPIDER;
            case "Чешуйница" -> EntityType.SILVERFISH;
            case "Ифрит" -> EntityType.BLAZE;
            case "Магмокуб" -> EntityType.MAGMA_CUBE;
            case "Дракон Края" -> EntityType.ENDER_DRAGON;
            case "Визер" -> EntityType.WITHER;
            case "Летучая мышь" -> EntityType.BAT;
            case "Ведьма" -> EntityType.WITCH;
            case "Эндермит" -> EntityType.ENDERMITE;
            case "Страж" -> EntityType.GUARDIAN;
            case "Шалкер" -> EntityType.SHULKER;
            case "Свинья" -> EntityType.PIG;
            case "Овца" -> EntityType.SHEEP;
            case "Корова" -> EntityType.COW;
            case "Курица" -> EntityType.CHICKEN;
            case "Спрут" -> EntityType.SQUID;
            case "Волк" -> EntityType.WOLF;
            case "Грибная корова" -> EntityType.MUSHROOM_COW;
            case "Снеговик" -> EntityType.SNOWMAN;
            case "Оцелот" -> EntityType.OCELOT;
            case "Железный голем" -> EntityType.IRON_GOLEM;
            case "Лошадь" -> EntityType.HORSE;
            case "Кролик" -> EntityType.RABBIT;
            case "Белый медведь" -> EntityType.POLAR_BEAR;
            case "Лама" -> EntityType.LLAMA;
            case "Попугай" -> EntityType.PARROT;
            case "Житель" -> EntityType.VILLAGER;
            case "Кристалл Края" -> EntityType.ENDER_CRYSTAL;
            case "Кадавр" -> EntityType.HUSK;
            case "Игрок" -> EntityType.PLAYER;
            case "Молния" -> EntityType.LIGHTNING;
            case "Плевок" -> EntityType.LLAMA_SPIT;
            case "Поплавок" -> EntityType.FISHING_HOOK;
            default -> null;
        };
    }

    public static String getName(EntityType entityType){
        return switch (entityType) {
            case DROPPED_ITEM -> "Падающий предмет";
            case EXPERIENCE_ORB -> "Опыт";
            case AREA_EFFECT_CLOUD -> "Облачность эффекта";
            case ELDER_GUARDIAN -> "Древний страж";
            case WITHER_SKELETON -> "Визер скелет";
            case STRAY -> "Зимогор";
            case EGG -> "Яйцо";
            case LEASH_HITCH -> "Пводок";
            case PAINTING -> "Картина";
            case ARROW -> "Стрела";
            case SNOWBALL -> "Снежок";
            case FIREBALL -> "Огненный шар";
            case SMALL_FIREBALL -> "Маленький огненный шар";
            case ENDER_PEARL -> "Жемчуг Края";
            case ENDER_SIGNAL -> "Сигнал Края";
            case SPLASH_POTION -> "Бутылка с зельем";
            case THROWN_EXP_BOTTLE -> "Бутылка с опытом";
            case ITEM_FRAME -> "Рамка";
            case WITHER_SKULL -> "Череп визера";
            case PRIMED_TNT -> "Горящий динамит";
            case FALLING_BLOCK -> "Падающий блок";
            case FIREWORK -> "Фейерверк";
            case SPECTRAL_ARROW -> "Спектральная стрела";
            case SHULKER_BULLET -> "Снаряд шалкера";
            case DRAGON_FIREBALL -> "Огненный шар дракона";
            case ZOMBIE_VILLAGER -> "Зомби житель";
            case SKELETON_HORSE -> "Скелет конь";
            case ZOMBIE_HORSE -> "Зомби конь";
            case ARMOR_STAND -> "Стойка для брони";
            case DONKEY -> "Осел";
            case MULE -> "Мул";
            case EVOKER_FANGS -> "Клыки призывателя";
            case EVOKER -> "Призыватель";
            case VEX -> "Досаждатель";
            case VINDICATOR -> "Разбойник";
            case ILLUSIONER -> "Иллюзионист";
            case MINECART_COMMAND -> "Вагонетка с комендным блоком";
            case BOAT -> "Лодка";
            case MINECART -> "Вагонетка";
            case MINECART_CHEST -> "Вагонетка с сундуком";
            case MINECART_FURNACE -> "Вагонетка с печкой";
            case MINECART_TNT -> "Вагонетка с ТНТ";
            case MINECART_HOPPER -> "Вагонетка с воронкой";
            case MINECART_MOB_SPAWNER -> "Вагонетка с спавнером";
            case CREEPER -> "Крипер";
            case SKELETON -> "Скелет";
            case SPIDER -> "Паук";
            case GIANT -> "Зомби гигант";
            case ZOMBIE -> "Зомби";
            case SLIME -> "Слизь";
            case GHAST -> "Гаст";
            case ZOGLIN -> "Свинозомби";
            case ENDERMAN -> "Эндермен";
            case CAVE_SPIDER -> "Пещерный паук";
            case SILVERFISH -> "Чешуйница";
            case BLAZE -> "Ифрит";
            case MAGMA_CUBE -> "Магмокуб";
            case ENDER_DRAGON -> "Дракон Края";
            case WITHER -> "Визер";
            case BAT -> "Летучая мышь";
            case WITCH -> "Ведьма";
            case ENDERMITE -> "Эндермит";
            case GUARDIAN -> "Страж";
            case SHULKER -> "Шалкер";
            case PIG -> "Свинья";
            case SHEEP -> "Овца";
            case COW -> "Корова";
            case CHICKEN -> "Курица";
            case SQUID -> "Спрут";
            case WOLF -> "Волк";
            case MUSHROOM_COW -> "Грибная корова";
            case SNOWMAN -> "Снеговик";
            case OCELOT -> "Оцелот";
            case IRON_GOLEM -> "Железный голем";
            case HORSE -> "Лошадь";
            case RABBIT -> "Кролик";
            case POLAR_BEAR -> "Белый медведь";
            case LLAMA -> "Лама";
            case PARROT -> "Попугай";
            case VILLAGER -> "Житель";
            case ENDER_CRYSTAL -> "Кристалл Края";
            case HUSK -> "Кадавр";
            case PLAYER -> "Игрок";
            case LIGHTNING -> "Молния";
            case LLAMA_SPIT -> "Плевок";
            case FISHING_HOOK -> "Поплавок";
            default -> entityType.toString();
        };
    }
}
