name: WAPIEnterpriseShowcase
version: '${version}'
main: me.penguinx13.wapi.WAPI
api-version: '1.19'
softdepend: [PlaceholderAPI]
commands:
  enterprise:
    description: Enterprise administration and utility suite.
    usage: /enterprise <subcommand>
permissions:
  wapi.enterprise:
    default: op
  wapi.enterprise.reload:
    default: op
  wapi.enterprise.user.create:
    default: op
  wapi.enterprise.user.info:
    default: op
  wapi.enterprise.user.delete:
    default: op
  wapi.enterprise.give:
    default: op
